sudo: required
services:
    - docker
before_install:
    - docker build -t anikhet/docker-react -f Dockerfile.dev .
script:
    - docker run -e CI=true anikhet/docker-react npm run test

language: generic